//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsWebService.StudentServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Student", Namespace="http://schemas.datacontract.org/2004/07/DTO")]
    [System.SerializableAttribute()]
    public partial class Student : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double MoneyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Money {
            get {
                return this.MoneyField;
            }
            set {
                if ((this.MoneyField.Equals(value) != true)) {
                    this.MoneyField = value;
                    this.RaisePropertyChanged("Money");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UID {
            get {
                return this.UIDField;
            }
            set {
                if ((this.UIDField.Equals(value) != true)) {
                    this.UIDField = value;
                    this.RaisePropertyChanged("UID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StudentServiceReference.IStudent")]
    public interface IStudent {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudent/AddMoneyUID", ReplyAction="http://tempuri.org/IStudent/AddMoneyUIDResponse")]
        int AddMoneyUID(int id, double money);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudent/AddMoneyUID", ReplyAction="http://tempuri.org/IStudent/AddMoneyUIDResponse")]
        System.Threading.Tasks.Task<int> AddMoneyUIDAsync(int id, double money);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudent/AddMoneyUsername", ReplyAction="http://tempuri.org/IStudent/AddMoneyUsernameResponse")]
        int AddMoneyUsername(string username, double money);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudent/AddMoneyUsername", ReplyAction="http://tempuri.org/IStudent/AddMoneyUsernameResponse")]
        System.Threading.Tasks.Task<int> AddMoneyUsernameAsync(string username, double money);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudent/AddMoneyStudent", ReplyAction="http://tempuri.org/IStudent/AddMoneyStudentResponse")]
        int AddMoneyStudent(WindowsFormsWebService.StudentServiceReference.Student student, double money);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudent/AddMoneyStudent", ReplyAction="http://tempuri.org/IStudent/AddMoneyStudentResponse")]
        System.Threading.Tasks.Task<int> AddMoneyStudentAsync(WindowsFormsWebService.StudentServiceReference.Student student, double money);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudent/GetAllStudents", ReplyAction="http://tempuri.org/IStudent/GetAllStudentsResponse")]
        WindowsFormsWebService.StudentServiceReference.Student[] GetAllStudents();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudent/GetAllStudents", ReplyAction="http://tempuri.org/IStudent/GetAllStudentsResponse")]
        System.Threading.Tasks.Task<WindowsFormsWebService.StudentServiceReference.Student[]> GetAllStudentsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudent/GetStudentByUID", ReplyAction="http://tempuri.org/IStudent/GetStudentByUIDResponse")]
        WindowsFormsWebService.StudentServiceReference.Student GetStudentByUID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudent/GetStudentByUID", ReplyAction="http://tempuri.org/IStudent/GetStudentByUIDResponse")]
        System.Threading.Tasks.Task<WindowsFormsWebService.StudentServiceReference.Student> GetStudentByUIDAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudent/GetStudentByUsername", ReplyAction="http://tempuri.org/IStudent/GetStudentByUsernameResponse")]
        WindowsFormsWebService.StudentServiceReference.Student GetStudentByUsername(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudent/GetStudentByUsername", ReplyAction="http://tempuri.org/IStudent/GetStudentByUsernameResponse")]
        System.Threading.Tasks.Task<WindowsFormsWebService.StudentServiceReference.Student> GetStudentByUsernameAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudent/ShowBalanceID", ReplyAction="http://tempuri.org/IStudent/ShowBalanceIDResponse")]
        string ShowBalanceID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudent/ShowBalanceID", ReplyAction="http://tempuri.org/IStudent/ShowBalanceIDResponse")]
        System.Threading.Tasks.Task<string> ShowBalanceIDAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudent/ShowBalanceStudent", ReplyAction="http://tempuri.org/IStudent/ShowBalanceStudentResponse")]
        string ShowBalanceStudent(WindowsFormsWebService.StudentServiceReference.Student student);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudent/ShowBalanceStudent", ReplyAction="http://tempuri.org/IStudent/ShowBalanceStudentResponse")]
        System.Threading.Tasks.Task<string> ShowBalanceStudentAsync(WindowsFormsWebService.StudentServiceReference.Student student);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudent/ShowBalanceUsername", ReplyAction="http://tempuri.org/IStudent/ShowBalanceUsernameResponse")]
        string ShowBalanceUsername(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudent/ShowBalanceUsername", ReplyAction="http://tempuri.org/IStudent/ShowBalanceUsernameResponse")]
        System.Threading.Tasks.Task<string> ShowBalanceUsernameAsync(string username);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStudentChannel : WindowsFormsWebService.StudentServiceReference.IStudent, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StudentClient : System.ServiceModel.ClientBase<WindowsFormsWebService.StudentServiceReference.IStudent>, WindowsFormsWebService.StudentServiceReference.IStudent {
        
        public StudentClient() {
        }
        
        public StudentClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StudentClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudentClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudentClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int AddMoneyUID(int id, double money) {
            return base.Channel.AddMoneyUID(id, money);
        }
        
        public System.Threading.Tasks.Task<int> AddMoneyUIDAsync(int id, double money) {
            return base.Channel.AddMoneyUIDAsync(id, money);
        }
        
        public int AddMoneyUsername(string username, double money) {
            return base.Channel.AddMoneyUsername(username, money);
        }
        
        public System.Threading.Tasks.Task<int> AddMoneyUsernameAsync(string username, double money) {
            return base.Channel.AddMoneyUsernameAsync(username, money);
        }
        
        public int AddMoneyStudent(WindowsFormsWebService.StudentServiceReference.Student student, double money) {
            return base.Channel.AddMoneyStudent(student, money);
        }
        
        public System.Threading.Tasks.Task<int> AddMoneyStudentAsync(WindowsFormsWebService.StudentServiceReference.Student student, double money) {
            return base.Channel.AddMoneyStudentAsync(student, money);
        }
        
        public WindowsFormsWebService.StudentServiceReference.Student[] GetAllStudents() {
            return base.Channel.GetAllStudents();
        }
        
        public System.Threading.Tasks.Task<WindowsFormsWebService.StudentServiceReference.Student[]> GetAllStudentsAsync() {
            return base.Channel.GetAllStudentsAsync();
        }
        
        public WindowsFormsWebService.StudentServiceReference.Student GetStudentByUID(int id) {
            return base.Channel.GetStudentByUID(id);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsWebService.StudentServiceReference.Student> GetStudentByUIDAsync(int id) {
            return base.Channel.GetStudentByUIDAsync(id);
        }
        
        public WindowsFormsWebService.StudentServiceReference.Student GetStudentByUsername(string username) {
            return base.Channel.GetStudentByUsername(username);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsWebService.StudentServiceReference.Student> GetStudentByUsernameAsync(string username) {
            return base.Channel.GetStudentByUsernameAsync(username);
        }
        
        public string ShowBalanceID(int id) {
            return base.Channel.ShowBalanceID(id);
        }
        
        public System.Threading.Tasks.Task<string> ShowBalanceIDAsync(int id) {
            return base.Channel.ShowBalanceIDAsync(id);
        }
        
        public string ShowBalanceStudent(WindowsFormsWebService.StudentServiceReference.Student student) {
            return base.Channel.ShowBalanceStudent(student);
        }
        
        public System.Threading.Tasks.Task<string> ShowBalanceStudentAsync(WindowsFormsWebService.StudentServiceReference.Student student) {
            return base.Channel.ShowBalanceStudentAsync(student);
        }
        
        public string ShowBalanceUsername(string username) {
            return base.Channel.ShowBalanceUsername(username);
        }
        
        public System.Threading.Tasks.Task<string> ShowBalanceUsernameAsync(string username) {
            return base.Channel.ShowBalanceUsernameAsync(username);
        }
    }
}
